/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Testimonial = IDL.Record({
  'name' : IDL.Text,
  'quote' : IDL.Text,
  'stars' : IDL.Nat8,
  'location' : IDL.Opt(IDL.Text),
});
export const FeaturesSection = IDL.Record({
  'checkmarkBullets' : IDL.Vec(IDL.Text),
  'lifestyleImageUrl' : IDL.Text,
  'bonusItems' : IDL.Vec(IDL.Text),
});
export const HeroSection = IDL.Record({
  'bookTitle' : IDL.Text,
  'tagline' : IDL.Text,
  'ctaButtonText' : IDL.Text,
  'ctaLink' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const PricingSection = IDL.Record({
  'originalPrice' : IDL.Nat,
  'upiLink' : IDL.Text,
  'qrCodeImageUrl' : IDL.Text,
  'discountedPrice' : IDL.Nat,
});
export const PageContent = IDL.Record({
  'featuresSection' : FeaturesSection,
  'ebookCoverImageUrl' : IDL.Text,
  'heroSection' : HeroSection,
  'pricingSection' : PricingSection,
  'testimonials' : IDL.Vec(Testimonial),
});

export const idlService = IDL.Service({
  'addOrUpdateTestimonial' : IDL.Func([Testimonial], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Text], [], []),
  'getPageContent' : IDL.Func([], [PageContent], ['query']),
  'getTestimonialsSortedByStars' : IDL.Func(
      [],
      [IDL.Vec(Testimonial)],
      ['query'],
    ),
  'replaceAllTestimonials' : IDL.Func([IDL.Vec(Testimonial)], [], []),
  'updateEbookCoverImageUrl' : IDL.Func([IDL.Text], [], []),
  'updateFeaturesSection' : IDL.Func([FeaturesSection], [], []),
  'updateHeroSection' : IDL.Func([HeroSection], [], []),
  'updatePricingSection' : IDL.Func([PricingSection], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Testimonial = IDL.Record({
    'name' : IDL.Text,
    'quote' : IDL.Text,
    'stars' : IDL.Nat8,
    'location' : IDL.Opt(IDL.Text),
  });
  const FeaturesSection = IDL.Record({
    'checkmarkBullets' : IDL.Vec(IDL.Text),
    'lifestyleImageUrl' : IDL.Text,
    'bonusItems' : IDL.Vec(IDL.Text),
  });
  const HeroSection = IDL.Record({
    'bookTitle' : IDL.Text,
    'tagline' : IDL.Text,
    'ctaButtonText' : IDL.Text,
    'ctaLink' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const PricingSection = IDL.Record({
    'originalPrice' : IDL.Nat,
    'upiLink' : IDL.Text,
    'qrCodeImageUrl' : IDL.Text,
    'discountedPrice' : IDL.Nat,
  });
  const PageContent = IDL.Record({
    'featuresSection' : FeaturesSection,
    'ebookCoverImageUrl' : IDL.Text,
    'heroSection' : HeroSection,
    'pricingSection' : PricingSection,
    'testimonials' : IDL.Vec(Testimonial),
  });
  
  return IDL.Service({
    'addOrUpdateTestimonial' : IDL.Func([Testimonial], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Text], [], []),
    'getPageContent' : IDL.Func([], [PageContent], ['query']),
    'getTestimonialsSortedByStars' : IDL.Func(
        [],
        [IDL.Vec(Testimonial)],
        ['query'],
      ),
    'replaceAllTestimonials' : IDL.Func([IDL.Vec(Testimonial)], [], []),
    'updateEbookCoverImageUrl' : IDL.Func([IDL.Text], [], []),
    'updateFeaturesSection' : IDL.Func([FeaturesSection], [], []),
    'updateHeroSection' : IDL.Func([HeroSection], [], []),
    'updatePricingSection' : IDL.Func([PricingSection], [], []),
  });
};

export const init = ({ IDL }) => { return []; };