/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FeaturesSection {
  'checkmarkBullets' : Array<string>,
  'lifestyleImageUrl' : string,
  'bonusItems' : Array<string>,
}
export interface HeroSection {
  'bookTitle' : string,
  'tagline' : string,
  'ctaButtonText' : string,
  'ctaLink' : string,
  'subtitle' : string,
}
export interface PageContent {
  'featuresSection' : FeaturesSection,
  'ebookCoverImageUrl' : string,
  'heroSection' : HeroSection,
  'pricingSection' : PricingSection,
  'testimonials' : Array<Testimonial>,
}
export interface PricingSection {
  'originalPrice' : bigint,
  'upiLink' : string,
  'qrCodeImageUrl' : string,
  'discountedPrice' : bigint,
}
export interface Testimonial {
  'name' : string,
  'quote' : string,
  'stars' : number,
  'location' : [] | [string],
}
export interface _SERVICE {
  'addOrUpdateTestimonial' : ActorMethod<[Testimonial], undefined>,
  'deleteTestimonial' : ActorMethod<[string], undefined>,
  'getPageContent' : ActorMethod<[], PageContent>,
  'getTestimonialsSortedByStars' : ActorMethod<[], Array<Testimonial>>,
  'replaceAllTestimonials' : ActorMethod<[Array<Testimonial>], undefined>,
  'updateEbookCoverImageUrl' : ActorMethod<[string], undefined>,
  'updateFeaturesSection' : ActorMethod<[FeaturesSection], undefined>,
  'updateHeroSection' : ActorMethod<[HeroSection], undefined>,
  'updatePricingSection' : ActorMethod<[PricingSection], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];