/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PricingSection {
    originalPrice: bigint;
    upiLink: string;
    qrCodeImageUrl: string;
    discountedPrice: bigint;
}
export interface HeroSection {
    bookTitle: string;
    tagline: string;
    ctaButtonText: string;
    ctaLink: string;
    subtitle: string;
}
export interface FeaturesSection {
    checkmarkBullets: Array<string>;
    lifestyleImageUrl: string;
    bonusItems: Array<string>;
}
export interface PageContent {
    featuresSection: FeaturesSection;
    ebookCoverImageUrl: string;
    heroSection: HeroSection;
    pricingSection: PricingSection;
    testimonials: Array<Testimonial>;
}
export interface Testimonial {
    name: string;
    quote: string;
    stars: number;
    location?: string;
}
export interface backendInterface {
    addOrUpdateTestimonial(testimonial: Testimonial): Promise<void>;
    deleteTestimonial(name: string): Promise<void>;
    getPageContent(): Promise<PageContent>;
    getTestimonialsSortedByStars(): Promise<Array<Testimonial>>;
    replaceAllTestimonials(newTestimonials: Array<Testimonial>): Promise<void>;
    updateEbookCoverImageUrl(newUrl: string): Promise<void>;
    updateFeaturesSection(newFeatures: FeaturesSection): Promise<void>;
    updateHeroSection(newHero: HeroSection): Promise<void>;
    updatePricingSection(newPricing: PricingSection): Promise<void>;
}
import type { FeaturesSection as _FeaturesSection, HeroSection as _HeroSection, PageContent as _PageContent, PricingSection as _PricingSection, Testimonial as _Testimonial } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addOrUpdateTestimonial(arg0: Testimonial): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateTestimonial(to_candid_Testimonial_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateTestimonial(to_candid_Testimonial_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteTestimonial(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0);
            return result;
        }
    }
    async getPageContent(): Promise<PageContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getPageContent();
                return from_candid_PageContent_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPageContent();
            return from_candid_PageContent_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonialsSortedByStars(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonialsSortedByStars();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonialsSortedByStars();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async replaceAllTestimonials(arg0: Array<Testimonial>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.replaceAllTestimonials(to_candid_vec_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.replaceAllTestimonials(to_candid_vec_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateEbookCoverImageUrl(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEbookCoverImageUrl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEbookCoverImageUrl(arg0);
            return result;
        }
    }
    async updateFeaturesSection(arg0: FeaturesSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeaturesSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeaturesSection(arg0);
            return result;
        }
    }
    async updateHeroSection(arg0: HeroSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHeroSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHeroSection(arg0);
            return result;
        }
    }
    async updatePricingSection(arg0: PricingSection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePricingSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePricingSection(arg0);
            return result;
        }
    }
}
function from_candid_PageContent_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PageContent): PageContent {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Testimonial_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Testimonial): Testimonial {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    featuresSection: _FeaturesSection;
    ebookCoverImageUrl: string;
    heroSection: _HeroSection;
    pricingSection: _PricingSection;
    testimonials: Array<_Testimonial>;
}): {
    featuresSection: FeaturesSection;
    ebookCoverImageUrl: string;
    heroSection: HeroSection;
    pricingSection: PricingSection;
    testimonials: Array<Testimonial>;
} {
    return {
        featuresSection: value.featuresSection,
        ebookCoverImageUrl: value.ebookCoverImageUrl,
        heroSection: value.heroSection,
        pricingSection: value.pricingSection,
        testimonials: from_candid_vec_n5(_uploadFile, _downloadFile, value.testimonials)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    quote: string;
    stars: number;
    location: [] | [string];
}): {
    name: string;
    quote: string;
    stars: number;
    location?: string;
} {
    return {
        name: value.name,
        quote: value.quote,
        stars: value.stars,
        location: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.location))
    };
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Testimonial>): Array<Testimonial> {
    return value.map((x)=>from_candid_Testimonial_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Testimonial_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Testimonial): _Testimonial {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    quote: string;
    stars: number;
    location?: string;
}): {
    name: string;
    quote: string;
    stars: number;
    location: [] | [string];
} {
    return {
        name: value.name,
        quote: value.quote,
        stars: value.stars,
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Testimonial>): Array<_Testimonial> {
    return value.map((x)=>to_candid_Testimonial_n1(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
